workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: app
    environment:
      xcode: 26.1
      node: 20
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install --repo-update
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Build iOS (Debug for Simulator)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.1' \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - app/ios/App/build/**/*.app
    publishing:
      email:
        recipients:
          - yeti@livewellandfully.com
        notify:
          success: true
          failure: true
